<a href="https://colab.research.google.com/github/lupiel/snippets_public/blob/main/colab/loop_groupby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as sns

In [2]:
df = sns.load_dataset("diamonds")

In [3]:
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [4]:
for group_name, df_group in df.groupby(["cut", "color", "clarity"]):
    df_group.reset_index(inplace=True, drop=True)
    print(group_name)
    print(df_group)
    break

('Ideal', 'D', 'IF')
    carat    cut color clarity  depth  table  price     x     y     z
0    0.51  Ideal     D      IF   62.0   56.0   3446  5.14  5.18  3.20
1    0.51  Ideal     D      IF   62.1   55.0   3446  5.12  5.13  3.19
2    0.53  Ideal     D      IF   61.5   54.0   3517  5.27  5.21  3.22
3    0.53  Ideal     D      IF   62.2   55.0   3812  5.17  5.19  3.22
4    0.63  Ideal     D      IF   61.2   53.0   3832  5.55  5.60  3.41
5    0.59  Ideal     D      IF   60.7   58.0   4161  5.45  5.49  3.32
6    0.59  Ideal     D      IF   60.9   57.0   4208  5.40  5.43  3.30
7    0.56  Ideal     D      IF   62.4   56.0   4216  5.24  5.28  3.28
8    0.56  Ideal     D      IF   61.9   57.0   4293  5.28  5.31  3.28
9    0.56  Ideal     D      IF   60.8   58.0   4632  5.35  5.31  3.24
10   0.59  Ideal     D      IF   60.9   60.0   4916  5.41  5.39  3.29
11   0.63  Ideal     D      IF   62.5   55.0   6549  5.47  5.50  3.43
12   0.63  Ideal     D      IF   62.5   55.0   6607  5.50  5.47  3.43
13   1.04  Ideal     D      IF   61.8   57.0  14494  6.49  6.52  4.02
14   1.04  Ideal     D      IF   61.8   57.0  14626  6.52  6.49  4.02
15   1.02  Ideal     D      IF   63.0   57.0  15575  6.39  6.35  4.01
16   1.06  Ideal     D      IF   61.2   57.0  15813  6.57  6.61  4.03
17   1.00  Ideal     D      IF   60.7   57.0  16469  6.44  6.48  3.92
18   1.07  Ideal     D      IF   60.9   54.0  17042  6.66  6.73  4.08
19   1.03  Ideal     D      IF   62.0   56.0  17590  6.55  6.44  4.03
20   0.27  Ideal     D      IF   62.4   56.0    893  4.15  4.12  2.58
21   0.31  Ideal     D      IF   61.1   56.0   1251  4.39  4.42  2.69
22   0.31  Ideal     D      IF   61.1   56.0   1310  4.42  4.39  2.69
23   0.31  Ideal     D      IF   60.5   57.0   1917  4.39  4.41  2.66
24   0.34  Ideal     D      IF   62.1   57.0   2287  4.46  4.52  2.79
25   0.34  Ideal     D      IF   59.8   57.0   2287  4.57  4.59  2.74
26   0.34  Ideal     D      IF   62.1   57.0   2346  4.52  4.46  2.79
27   0.34  Ideal     D      IF   59.8   57.0   2346  4.59  4.57  2.74